"""
Report Generator
Produces Markdown, JSON, and plain-text reports from meeting data.
"""

import json
from datetime import datetime
from typing import Dict, Any, List


def _timestamp() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


# ─── Markdown ─────────────────────────────────────────────────────────────────
def generate_markdown_report(title: str, transcript: str, result: Dict[str, Any]) -> str:
    tasks: List[Dict] = result.get("tasks", [])
    action_items: List[str] = result.get("action_items", [])
    summary: str = result.get("summary", "")

    lines = [
        f"# 📋 Meeting Report: {title}",
        f"> Generated: {_timestamp()}",
        "",
        "---",
        "",
        "## 📝 Summary",
        "",
        summary or "_No summary available._",
        "",
        "---",
        "",
        "## ✅ Action Items",
        "",
    ]

    if action_items:
        for item in action_items:
            lines.append(f"- {item}")
    else:
        lines.append("_No action items found._")

    lines += [
        "",
        "---",
        "",
        "## 📌 Tasks",
        "",
        "| # | Task | Owner | Priority | Due Date | Status |",
        "|---|------|-------|----------|----------|--------|",
    ]

    if tasks:
        for i, t in enumerate(tasks, 1):
            priority_emoji = {"High": "🔴", "Medium": "🟡", "Low": "🟢"}.get(t.get("priority", ""), "⚪")
            lines.append(
                f"| {i} | {t.get('task','')[:80]} | {t.get('owner','Unassigned')} "
                f"| {priority_emoji} {t.get('priority','Medium')} "
                f"| {t.get('due_date','Not specified')} "
                f"| {t.get('status','Pending')} |"
            )
    else:
        lines.append("| — | No tasks extracted | — | — | — | — |")

    lines += [
        "",
        "---",
        "",
        "## 🎙️ Full Transcript",
        "",
        "```",
        transcript[:3000] + ("…" if len(transcript) > 3000 else ""),
        "```",
        "",
        "---",
        f"*Report generated by Meeting-to-Task Automation System • {_timestamp()}*",
    ]

    return "\n".join(lines)


# ─── JSON ─────────────────────────────────────────────────────────────────────
def generate_json_report(title: str, transcript: str, result: Dict[str, Any]) -> str:
    payload = {
        "meeting_title": title,
        "generated_at": _timestamp(),
        "summary": result.get("summary", ""),
        "tasks": result.get("tasks", []),
        "action_items": result.get("action_items", []),
        "transcript_snippet": transcript[:500],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)


# ─── Plain Text ───────────────────────────────────────────────────────────────
def generate_txt_report(title: str, transcript: str, result: Dict[str, Any]) -> str:
    tasks = result.get("tasks", [])
    action_items = result.get("action_items", [])
    summary = result.get("summary", "")

    sep = "=" * 60
    lines = [
        sep,
        f"MEETING REPORT: {title.upper()}",
        f"Generated: {_timestamp()}",
        sep,
        "",
        "SUMMARY",
        "-" * 40,
        summary or "No summary available.",
        "",
        "ACTION ITEMS",
        "-" * 40,
    ]

    if action_items:
        for i, item in enumerate(action_items, 1):
            lines.append(f"  {i}. {item}")
    else:
        lines.append("  No action items found.")

    lines += ["", "TASKS", "-" * 40]

    if tasks:
        for i, t in enumerate(tasks, 1):
            lines += [
                f"  Task {i}:",
                f"    Description : {t.get('task', '')}",
                f"    Owner       : {t.get('owner', 'Unassigned')}",
                f"    Priority    : {t.get('priority', 'Medium')}",
                f"    Due Date    : {t.get('due_date', 'Not specified')}",
                f"    Status      : {t.get('status', 'Pending')}",
                "",
            ]
    else:
        lines.append("  No tasks extracted.")

    lines += [
        "",
        "TRANSCRIPT (first 1000 chars)",
        "-" * 40,
        transcript[:1000] + ("..." if len(transcript) > 1000 else ""),
        "",
        sep,
        "End of Report",
        sep,
    ]

    return "\n".join(lines)
